default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: echosight_app_development

test:
  <<: *default
  database: echosight_app_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>