Queue Monitor - every 5 minutes:
  cron: "*/5 * * * *"
  class: "QueueMonitorJob"

Fetch Tweets:
  cron: "<%= CronExpressionGenerator.for_interval(ApplicationConstants::TWITTER_FETCH_INTERVAL) %>"
  class: "Twitter::TweetsFetcherJob"

Sync Subscriptions - every 1 hour:
  cron: "0 * * * *"
  class: "SubscriptionSyncJob"

Regenerate User Public Page Cache - every 3 hours:
  cron: "0 */3 * * *"
  class: "RegenerateUserPublicPageCacheJob"

Users Without Subscription Email - every 1 day:
  cron: "0 0 * * *"
  class: "UsersWithoutSubscriptionEmailJob"

capture_leaderboard_job:
  cron: "0 * * * *"
  class: "Twitter::CaptureLeaderboardJob"

identity_notifications_job:
  cron: "0 10 * * *"
  class: "IdentityNotificationJob"
  tz: "Australia/Sydney"
